# Site settings
title: CAL Wiki
author: Wiki Team
description: "Wiki for the Divine Dungeon Expanded Universe"

# Build settings
remote_theme: jekyll/minima



collections:
  - Atlas
  - Bestiary
  - Books
  - Characters
  - Lexicon

# Exclude these files from production site
exclude:
  - README.md

# Include these files from production site
include:
  _Atlas
  _Bestiary
  _Books
  _Characters
  _Lexicon