# Site settings
title: CAL Wiki
author: Wiki Team
description: "Wiki for the Divine Dungeon Expanded Universe"

# Build settings
remote_theme: jekyll/minima


collections:
  Atlas:
    output: true
    permalink: /:collection/:name
  Bestiary:
    output: true
    permalink: /:collection/:name
  Books:
    output: true
    permalink: /:collection/:name
  Characters:
    output: true
    permalink: /:collection/:name
  Lexicon:
    output: true
    permalink: /:collection/:name

# Exclude these files from production site
exclude:
  - README.md

# Include these files from production site
include:
  _Atlas
  _Bestiary
  _Books
  _Characters
  _Lexicon

# Plugins
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true